const fs = require("fs-extra");
const glob = require("glob");
const path = require("path");
const { optimize } = require("svgo");

async function build() {
  const files = glob.sync("assets/icons/*.svg");
  const mapping = {};

  for (const f of files) {
    let svg = await fs.readFile(f, "utf8");
    try {
      svg = optimize(svg, { path: f }).data;
    } catch (e) {
      // if svgo fails, fall back to raw content
    }

    // percent-encode SVG for data URI
    const dataUri = "data:image/svg+xml;utf8," + encodeURIComponent(svg);
    const id = path.basename(f, ".svg");
    mapping[id] = dataUri;
  }

  const moduleContent = `// generated by scripts/build-icons.js\nexport default ${JSON.stringify(mapping, null, 2)};\n`;
  await fs.outputFile("lib/util/generated-icons.js", moduleContent);
  console.log("Wrote lib/util/generated-icons.js");
}

build().catch((err) => {
  console.error(err);
  process.exit(1);
});
